"""
Central configuration for the Hercules newsletter automation.

Nothing in here should require touching other files when you change it.
Fill in the real values via environment variables (or GitHub Actions
secrets) before running for real -- never hardcode API keys or DB
credentials in this file.
"""

import os

# --- Data source mode -------------------------------------------------
# "api"    -> queries the hercules.works DB directly through the live API.
#             This is the only mode the Thursday automation runs in --
#             there is no CSV export step, live or otherwise.
# "sample" -> reads recipients from sample_data/sample_recipients.json.
#             Local-testing-only stand-in for the real DB, never used in
#             production.
DATA_SOURCE_MODE = os.environ.get("NEWSLETTER_DATA_SOURCE", "api")

# --- Live API settings (used when DATA_SOURCE_MODE == "api") ----------
# TODO (before first live send): confirm the actual endpoint path, auth
# header shape, and response fields with whoever owns the hercules.works
# backend, then finish _get_recipients_from_api() in data_sources.py.
HERCULES_API_BASE = os.environ.get("HERCULES_API_BASE", "")
HERCULES_API_KEY = os.environ.get("HERCULES_API_KEY", "")
POSEIDON_API_BASE = os.environ.get("POSEIDON_API_BASE", "")
POSEIDON_API_KEY = os.environ.get("POSEIDON_API_KEY", "")

# --- Sample data path (only used when DATA_SOURCE_MODE == "sample") ---
SAMPLE_RECIPIENTS_PATH = os.environ.get(
    "SAMPLE_RECIPIENTS_PATH", "sample_data/sample_recipients.json"
)

# The human-approved weekly content file. You feed the week's report to
# Claude in chat (see .claude/skills/weekly-newsletter/SKILL.md), review
# the rendered preview, and once you approve it Claude saves the final
# JSON here. This is NOT auto-generated by the pipeline itself -- picking
# the finding and drafting the copy stays a human-in-the-loop step.
WEEKLY_CONTENT_PATH = os.environ.get(
    "WEEKLY_CONTENT_PATH", "content/weekly_content.json"
)

# Every non-dry-run send archives a dated copy of what was actually sent
# into this directory, so git history alone tells you what went out and
# when even after weekly_content.json is overwritten by the next issue.
SENT_ARCHIVE_DIR = "content/sent"

# --- Illustration settings ---------------------------------------------
# "placeholder"  -> builds a simple inline-SVG stat graphic from the
#                   content's hero_stat_value / hero_stat_label. Works
#                   today, no external dependency. This is the current
#                   mode -- see illustrations.py.
# "brand_asset"  -> uses the real hercules.works blog illustration/design
#                   system once it's handed off. Switch to this mode when
#                   that design is ready; nothing else needs to change.
ILLUSTRATION_MODE = os.environ.get("NEWSLETTER_ILLUSTRATION_MODE", "placeholder")

# Only used in "brand_asset" mode: a URL (or set of URLs, once the real
# design is known) to the hercules.works illustration asset for this
# week's issue. Left blank until the design handoff happens.
BRAND_ILLUSTRATION_ASSET_URL = os.environ.get("BRAND_ILLUSTRATION_ASSET_URL", "")

# Placeholder brand accent color for the interim illustration. Replace
# with the real hercules.works blog brand token once that design is
# delivered (see README "Pending: real brand design").
BRAND_ACCENT_COLOR = os.environ.get("BRAND_ACCENT_COLOR", "#5B47F5")

# --- ESP (email service provider) settings -----------------------------
ESP_PROVIDER = os.environ.get("ESP_PROVIDER", "sendgrid")  # sendgrid | mailchimp
ESP_API_KEY = os.environ.get("ESP_API_KEY", "")
FROM_EMAIL = os.environ.get("FROM_EMAIL", "newsletter@hercules.works")
FROM_NAME = os.environ.get("FROM_NAME", "Hercules.works")
SUBJECT_PREFIX = ""  # keep empty; subject line should be the stat itself

# --- Segmentation -------------------------------------------------------
# Users with no login in this many days are treated as "dormant" and can
# get a different subject line / CTA (handled in render.py).
DORMANT_THRESHOLD_DAYS = 21

# --- Verification thresholds --------------------------------------------
# Hard stops before a send is allowed to go out. Tune these as you learn
# what "normal" looks like for your platform.
MIN_EXPECTED_RECIPIENTS = 10
MAX_EXPECTED_RECIPIENTS = 2_000_000  # sanity ceiling, not a real limit

# A "2 minute read" is roughly 300-400 words at average reading speed.
# These bound the body text (hook + insight paragraph + supporting
# points + closing line) so a draft that's ballooned or gotten too thin
# gets caught before it sends.
MIN_WORD_COUNT = 220
MAX_WORD_COUNT = 480

# House style checks -- matches your stated copy preferences. Any of
# these appearing in the draft fails verification and blocks the send.
BANNED_PHRASES = [
    "dive into", "delve", "unlock", "in today's fast-paced world",
    "game-changer", "game changer", "unpack", "leverage",
    "in this article", "in this newsletter", "let's explore",
    "it's important to note", "when it comes to",
]

# --- Operational ----------------------------------------------------------
DRY_RUN = os.environ.get("NEWSLETTER_DRY_RUN", "true").lower() == "true"
LOG_DIR = "logs"
